/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGateRouteImport } from './routes/admin/_gate'
import { Route as LangTransfersRouteImport } from './routes/$lang/transfers'
import { Route as LangToursRouteImport } from './routes/$lang/tours'
import { Route as LangTermsRouteImport } from './routes/$lang/terms'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangHikingRouteImport } from './routes/$lang/hiking'
import { Route as LangFaqRouteImport } from './routes/$lang/faq'
import { Route as LangCookiesRouteImport } from './routes/$lang/cookies'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangBookRouteImport } from './routes/$lang/book'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as AdminGateIndexRouteImport } from './routes/admin/_gate/index'
import { Route as AdminGateTestimonialsRouteImport } from './routes/admin/_gate/testimonials'
import { Route as AdminGateSettingsRouteImport } from './routes/admin/_gate/settings'
import { Route as AdminGateProfileRouteImport } from './routes/admin/_gate/profile'
import { Route as AdminGateMessagesRouteImport } from './routes/admin/_gate/messages'
import { Route as AdminGateMediaRouteImport } from './routes/admin/_gate/media'
import { Route as AdminGateFaqRouteImport } from './routes/admin/_gate/faq'
import { Route as AdminGateBookingsRouteImport } from './routes/admin/_gate/bookings'
import { Route as LangSSlugRouteImport } from './routes/$lang/s.$slug'
import { Route as AdminGateServicesIndexRouteImport } from './routes/admin/_gate/services/index'
import { Route as AdminGateBlogIndexRouteImport } from './routes/admin/_gate/blog/index'
import { Route as AdminGateServicesIdRouteImport } from './routes/admin/_gate/services/$id'
import { Route as AdminGateBlogIdRouteImport } from './routes/admin/_gate/blog/$id'
import { Route as LangBookConfirmedRefRouteImport } from './routes/$lang/book.confirmed.$ref'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGateRoute = AdminGateRouteImport.update({
  id: '/admin/_gate',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTransfersRoute = LangTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangToursRoute = LangToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangHikingRoute = LangHikingRouteImport.update({
  id: '/hiking',
  path: '/hiking',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCookiesRoute = LangCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBookRoute = LangBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminGateIndexRoute = AdminGateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateTestimonialsRoute = AdminGateTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateSettingsRoute = AdminGateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateProfileRoute = AdminGateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateMessagesRoute = AdminGateMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateMediaRoute = AdminGateMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateFaqRoute = AdminGateFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateBookingsRoute = AdminGateBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminGateRoute,
} as any)
const LangSSlugRoute = LangSSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminGateServicesIndexRoute = AdminGateServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateBlogIndexRoute = AdminGateBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateServicesIdRoute = AdminGateServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AdminGateRoute,
} as any)
const AdminGateBlogIdRoute = AdminGateBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminGateRoute,
} as any)
const LangBookConfirmedRefRoute = LangBookConfirmedRefRouteImport.update({
  id: '/confirmed/$ref',
  path: '/confirmed/$ref',
  getParentRoute: () => LangBookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/book': typeof LangBookRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/hiking': typeof LangHikingRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/tours': typeof LangToursRoute
  '/$lang/transfers': typeof LangTransfersRoute
  '/admin': typeof AdminGateRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/s/$slug': typeof LangSSlugRoute
  '/admin/bookings': typeof AdminGateBookingsRoute
  '/admin/faq': typeof AdminGateFaqRoute
  '/admin/media': typeof AdminGateMediaRoute
  '/admin/messages': typeof AdminGateMessagesRoute
  '/admin/profile': typeof AdminGateProfileRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/admin/testimonials': typeof AdminGateTestimonialsRoute
  '/admin/': typeof AdminGateIndexRoute
  '/$lang/book/confirmed/$ref': typeof LangBookConfirmedRefRoute
  '/admin/blog/$id': typeof AdminGateBlogIdRoute
  '/admin/services/$id': typeof AdminGateServicesIdRoute
  '/admin/blog/': typeof AdminGateBlogIndexRoute
  '/admin/services/': typeof AdminGateServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/book': typeof LangBookRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/hiking': typeof LangHikingRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/tours': typeof LangToursRoute
  '/$lang/transfers': typeof LangTransfersRoute
  '/admin/login': typeof AdminLoginRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/s/$slug': typeof LangSSlugRoute
  '/admin/bookings': typeof AdminGateBookingsRoute
  '/admin/faq': typeof AdminGateFaqRoute
  '/admin/media': typeof AdminGateMediaRoute
  '/admin/messages': typeof AdminGateMessagesRoute
  '/admin/profile': typeof AdminGateProfileRoute
  '/admin/settings': typeof AdminGateSettingsRoute
  '/admin/testimonials': typeof AdminGateTestimonialsRoute
  '/admin': typeof AdminGateIndexRoute
  '/$lang/book/confirmed/$ref': typeof LangBookConfirmedRefRoute
  '/admin/blog/$id': typeof AdminGateBlogIdRoute
  '/admin/services/$id': typeof AdminGateServicesIdRoute
  '/admin/blog': typeof AdminGateBlogIndexRoute
  '/admin/services': typeof AdminGateServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/book': typeof LangBookRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/cookies': typeof LangCookiesRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/hiking': typeof LangHikingRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/tours': typeof LangToursRoute
  '/$lang/transfers': typeof LangTransfersRoute
  '/admin/_gate': typeof AdminGateRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/s/$slug': typeof LangSSlugRoute
  '/admin/_gate/bookings': typeof AdminGateBookingsRoute
  '/admin/_gate/faq': typeof AdminGateFaqRoute
  '/admin/_gate/media': typeof AdminGateMediaRoute
  '/admin/_gate/messages': typeof AdminGateMessagesRoute
  '/admin/_gate/profile': typeof AdminGateProfileRoute
  '/admin/_gate/settings': typeof AdminGateSettingsRoute
  '/admin/_gate/testimonials': typeof AdminGateTestimonialsRoute
  '/admin/_gate/': typeof AdminGateIndexRoute
  '/$lang/book/confirmed/$ref': typeof LangBookConfirmedRefRoute
  '/admin/_gate/blog/$id': typeof AdminGateBlogIdRoute
  '/admin/_gate/services/$id': typeof AdminGateServicesIdRoute
  '/admin/_gate/blog/': typeof AdminGateBlogIndexRoute
  '/admin/_gate/services/': typeof AdminGateServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/book'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/faq'
    | '/$lang/hiking'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/tours'
    | '/$lang/transfers'
    | '/admin'
    | '/admin/login'
    | '/$lang/'
    | '/$lang/s/$slug'
    | '/admin/bookings'
    | '/admin/faq'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
    | '/$lang/book/confirmed/$ref'
    | '/admin/blog/$id'
    | '/admin/services/$id'
    | '/admin/blog/'
    | '/admin/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/book'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/faq'
    | '/$lang/hiking'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/tours'
    | '/$lang/transfers'
    | '/admin/login'
    | '/$lang'
    | '/$lang/s/$slug'
    | '/admin/bookings'
    | '/admin/faq'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin'
    | '/$lang/book/confirmed/$ref'
    | '/admin/blog/$id'
    | '/admin/services/$id'
    | '/admin/blog'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/book'
    | '/$lang/contact'
    | '/$lang/cookies'
    | '/$lang/faq'
    | '/$lang/hiking'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/tours'
    | '/$lang/transfers'
    | '/admin/_gate'
    | '/admin/login'
    | '/$lang/'
    | '/$lang/s/$slug'
    | '/admin/_gate/bookings'
    | '/admin/_gate/faq'
    | '/admin/_gate/media'
    | '/admin/_gate/messages'
    | '/admin/_gate/profile'
    | '/admin/_gate/settings'
    | '/admin/_gate/testimonials'
    | '/admin/_gate/'
    | '/$lang/book/confirmed/$ref'
    | '/admin/_gate/blog/$id'
    | '/admin/_gate/services/$id'
    | '/admin/_gate/blog/'
    | '/admin/_gate/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminGateRoute: typeof AdminGateRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gate': {
      id: '/admin/_gate'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/transfers': {
      id: '/$lang/transfers'
      path: '/transfers'
      fullPath: '/$lang/transfers'
      preLoaderRoute: typeof LangTransfersRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/tours': {
      id: '/$lang/tours'
      path: '/tours'
      fullPath: '/$lang/tours'
      preLoaderRoute: typeof LangToursRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/hiking': {
      id: '/$lang/hiking'
      path: '/hiking'
      fullPath: '/$lang/hiking'
      preLoaderRoute: typeof LangHikingRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/cookies': {
      id: '/$lang/cookies'
      path: '/cookies'
      fullPath: '/$lang/cookies'
      preLoaderRoute: typeof LangCookiesRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/book': {
      id: '/$lang/book'
      path: '/book'
      fullPath: '/$lang/book'
      preLoaderRoute: typeof LangBookRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/_gate/': {
      id: '/admin/_gate/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminGateIndexRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/testimonials': {
      id: '/admin/_gate/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminGateTestimonialsRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/settings': {
      id: '/admin/_gate/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminGateSettingsRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/profile': {
      id: '/admin/_gate/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminGateProfileRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/messages': {
      id: '/admin/_gate/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminGateMessagesRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/media': {
      id: '/admin/_gate/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminGateMediaRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/faq': {
      id: '/admin/_gate/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminGateFaqRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/bookings': {
      id: '/admin/_gate/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminGateBookingsRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/$lang/s/$slug': {
      id: '/$lang/s/$slug'
      path: '/s/$slug'
      fullPath: '/$lang/s/$slug'
      preLoaderRoute: typeof LangSSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/_gate/services/': {
      id: '/admin/_gate/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminGateServicesIndexRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/blog/': {
      id: '/admin/_gate/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminGateBlogIndexRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/services/$id': {
      id: '/admin/_gate/services/$id'
      path: '/services/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminGateServicesIdRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/admin/_gate/blog/$id': {
      id: '/admin/_gate/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminGateBlogIdRouteImport
      parentRoute: typeof AdminGateRoute
    }
    '/$lang/book/confirmed/$ref': {
      id: '/$lang/book/confirmed/$ref'
      path: '/confirmed/$ref'
      fullPath: '/$lang/book/confirmed/$ref'
      preLoaderRoute: typeof LangBookConfirmedRefRouteImport
      parentRoute: typeof LangBookRoute
    }
  }
}

interface LangBookRouteChildren {
  LangBookConfirmedRefRoute: typeof LangBookConfirmedRefRoute
}

const LangBookRouteChildren: LangBookRouteChildren = {
  LangBookConfirmedRefRoute: LangBookConfirmedRefRoute,
}

const LangBookRouteWithChildren = LangBookRoute._addFileChildren(
  LangBookRouteChildren,
)

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBookRoute: typeof LangBookRouteWithChildren
  LangContactRoute: typeof LangContactRoute
  LangCookiesRoute: typeof LangCookiesRoute
  LangFaqRoute: typeof LangFaqRoute
  LangHikingRoute: typeof LangHikingRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangTermsRoute: typeof LangTermsRoute
  LangToursRoute: typeof LangToursRoute
  LangTransfersRoute: typeof LangTransfersRoute
  LangIndexRoute: typeof LangIndexRoute
  LangSSlugRoute: typeof LangSSlugRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBookRoute: LangBookRouteWithChildren,
  LangContactRoute: LangContactRoute,
  LangCookiesRoute: LangCookiesRoute,
  LangFaqRoute: LangFaqRoute,
  LangHikingRoute: LangHikingRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangTermsRoute: LangTermsRoute,
  LangToursRoute: LangToursRoute,
  LangTransfersRoute: LangTransfersRoute,
  LangIndexRoute: LangIndexRoute,
  LangSSlugRoute: LangSSlugRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface AdminGateRouteChildren {
  AdminGateBookingsRoute: typeof AdminGateBookingsRoute
  AdminGateFaqRoute: typeof AdminGateFaqRoute
  AdminGateMediaRoute: typeof AdminGateMediaRoute
  AdminGateMessagesRoute: typeof AdminGateMessagesRoute
  AdminGateProfileRoute: typeof AdminGateProfileRoute
  AdminGateSettingsRoute: typeof AdminGateSettingsRoute
  AdminGateTestimonialsRoute: typeof AdminGateTestimonialsRoute
  AdminGateIndexRoute: typeof AdminGateIndexRoute
  AdminGateBlogIdRoute: typeof AdminGateBlogIdRoute
  AdminGateServicesIdRoute: typeof AdminGateServicesIdRoute
  AdminGateBlogIndexRoute: typeof AdminGateBlogIndexRoute
  AdminGateServicesIndexRoute: typeof AdminGateServicesIndexRoute
}

const AdminGateRouteChildren: AdminGateRouteChildren = {
  AdminGateBookingsRoute: AdminGateBookingsRoute,
  AdminGateFaqRoute: AdminGateFaqRoute,
  AdminGateMediaRoute: AdminGateMediaRoute,
  AdminGateMessagesRoute: AdminGateMessagesRoute,
  AdminGateProfileRoute: AdminGateProfileRoute,
  AdminGateSettingsRoute: AdminGateSettingsRoute,
  AdminGateTestimonialsRoute: AdminGateTestimonialsRoute,
  AdminGateIndexRoute: AdminGateIndexRoute,
  AdminGateBlogIdRoute: AdminGateBlogIdRoute,
  AdminGateServicesIdRoute: AdminGateServicesIdRoute,
  AdminGateBlogIndexRoute: AdminGateBlogIndexRoute,
  AdminGateServicesIndexRoute: AdminGateServicesIndexRoute,
}

const AdminGateRouteWithChildren = AdminGateRoute._addFileChildren(
  AdminGateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminGateRoute: AdminGateRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
