-- ===== Enter Gauja categories (Vadlīnijas 2025 colours) =====
INSERT INTO public.enter_gauja_categories (key, name_lv, name_en, name_es, description_lv, description_en, description_es, icon_name, color_hex, sort_order) VALUES
 ('nature','Daba','Nature','Naturaleza','Meži, upes un dabas takas Gaujas ielejā.','Forests, rivers and nature trails in the Gauja valley.','Bosques, ríos y senderos naturales en el valle del Gauja.','deer','#4F6F19',1),
 ('history','Vēsture','History','Historia','Viduslaiku pilis, muižas un senās apmetnes.','Medieval castles, manors and ancient settlements.','Castillos medievales, mansiones y asentamientos antiguos.','tower','#D1701A',2),
 ('culture','Kultūra','Culture','Cultura','Amatniecība, muzeji un vietējie stāsti.','Crafts, museums and local stories.','Artesanía, museos e historias locales.','star','#51869D',3),
 ('action','Piedzīvojums','Action','Aventura','Aktīvi maršruti un piedzīvojumi brīvā dabā.','Active routes and outdoor adventures.','Rutas activas y aventuras al aire libre.','lightning','#F05366',4),
 ('getaround','Gauja Get-around','Gauja Get-around','Gauja Get-around','Transfēri un pārvietošanās Gaujas reģionā.','Transfers and getting around the Gauja region.','Traslados y desplazamientos por la región del Gauja.','horse','#6987B6',5)
ON CONFLICT (key) DO NOTHING;

-- ===== Guide profile =====
-- NOTE: biography text below is PLACEHOLDER copy — Ilze replaces it via /admin/profile.
INSERT INTO public.profile (
  full_name, role_lv, role_en, role_es,
  short_bio_lv, short_bio_en, short_bio_es,
  bio_lv, bio_en, bio_es,
  phone, email, whatsapp, languages_spoken, certifications, years_of_experience
)
SELECT
 'Ilze Gulbe',
 'Sertificēta gide un ekskursiju vadītāja','Certified guide and tour leader','Guía certificada y organizadora de excursiones',
 'Sertificēta gide ar vairāk nekā 10 gadu pieredzi Gaujas reģionā. Vadu ekskursijas, pārgājienus un piedāvāju privātos transfērus.',
 'Certified guide with over 10 years of experience in the Gauja region. I lead tours and hikes and offer private transfers.',
 'Guía certificada con más de 10 años de experiencia en la región del Gauja. Dirijo excursiones, caminatas y ofrezco traslados privados.',
 E'Esmu Ilze — dzimusi un augusi Gaujas krastos. Jau vairāk nekā desmit gadus vadu ekskursijas un pārgājienus Siguldā, Cēsīs, Līgatnē un Gaujas Nacionālajā parkā.\n\nMani visvairāk aizrauj stāsti, kas paliek aiz akmens mūriem un meža takām: kāpēc pils tika celta tieši šajā līkumā, kā smilšakmens klintis veidojušās tūkstošiem gadu, ko cilvēki šeit darīja pirms simts gadiem. Katrā maršrutā cenšos savienot ainavu ar konkrētu, pārbaudītu stāstu.\n\nStrādāju ar nelielām grupām — līdz astoņiem cilvēkiem ekskursijās un līdz desmit pārgājienos. Tā varam apstāties tur, kur gribas, pielāgot tempu un runāt, nevis klausīties skaļruni. Maršrutu vienmēr saskaņoju iepriekš: ar bērniem ejam vienu ceļu, ar pieredzējušiem gājējiem — citu.\n\nRunāju latviski, angliski, krieviski un spāniski. Ja plānojat dienu Gaujas ielejā un nezināt, ar ko sākt — uzrakstiet, un kopā saliksim maršrutu.',
 E'I am Ilze — born and raised on the banks of the Gauja. For more than ten years I have been leading tours and hikes in Sigulda, Cēsis, Līgatne and the Gauja National Park.\n\nWhat fascinates me most are the stories behind stone walls and forest trails: why a castle was built in this particular bend of the river, how the sandstone cliffs formed over thousands of years, what people did here a century ago.\n\nI work with small groups — up to eight people on tours and up to ten on hikes — so we can stop where we want and keep a comfortable pace. Routes are always agreed in advance.\n\nI speak Latvian, English, Russian and Spanish. If you are planning a day in the Gauja valley, write to me and we will put the route together.',
 E'Soy Ilze, nacida y criada a orillas del Gauja. Desde hace más de diez años dirijo excursiones y caminatas en Sigulda, Cēsis, Līgatne y el Parque Nacional del Gauja.\n\nLo que más me apasiona son las historias que se esconden tras los muros de piedra y los senderos del bosque: por qué se construyó un castillo justo en ese meandro, cómo se formaron los acantilados de arenisca.\n\nTrabajo con grupos pequeños —hasta ocho personas en excursiones y diez en caminatas—, así podemos parar donde queramos y mantener un ritmo cómodo.\n\nHablo letón, inglés, ruso y español. Si planea un día en el valle del Gauja, escríbame y armamos la ruta juntos.',
 '+371 29299354','ilze.gulbe@creatus.lv','+371 29299354',
 ARRAY['lv','en','ru','es'],
 '[{"name":"Sertificēta gide","year":2015,"issuer":"Latvijas Republika"}]'::jsonb,
 10
WHERE NOT EXISTS (SELECT 1 FROM public.profile);

-- ===== Site settings =====
INSERT INTO public.site_settings (key, value, description) VALUES
 ('contact_email','"ilze.gulbe@creatus.lv"','Publiskā e-pasta adrese'),
 ('contact_phone','"+371 29299354"','Publiskais tālrunis'),
 ('contact_whatsapp','"+371 29299354"','WhatsApp numurs'),
 ('social_facebook','""','Facebook profila saite'),
 ('social_instagram','""','Instagram profila saite'),
 ('hero_headline','{"lv":"Gaujas ieleja ar vietējo gidi","en":"The Gauja valley with a local guide","es":"El valle del Gauja con una guía local"}','Galvenā virsraksta teksts'),
 ('hero_subline','{"lv":"Ekskursijas, pārgājieni un privātie transfēri Siguldā, Cēsīs un Līgatnē.","en":"Tours, hikes and private transfers in Sigulda, Cēsis and Līgatne.","es":"Excursiones, caminatas y traslados privados en Sigulda, Cēsis y Līgatne."}','Apakšvirsraksts'),
 ('footer_text','{"lv":"Sertificēta gide Ilze Gulbe · Gaujas Nacionālais parks","en":"Certified guide Ilze Gulbe · Gauja National Park","es":"Guía certificada Ilze Gulbe · Parque Nacional del Gauja"}','Kājenes teksts'),
 ('google_analytics_id','""','Google Analytics mērījumu ID'),
 ('booking_notification_email','"ilze.gulbe@creatus.lv"','Adrese rezervāciju paziņojumiem'),
 ('default_language','"lv"','Noklusējuma valoda')
ON CONFLICT (key) DO NOTHING;

-- ===== Services =====
INSERT INTO public.services (
 type, slug_lv, slug_en, slug_es, title_lv, title_en, title_es,
 short_description_lv, short_description_en, short_description_es,
 description_lv, description_en, description_es,
 duration_minutes, price_from_eur, price_per_person, min_persons, max_persons,
 enter_gauja_categories, difficulty, location_name, location_lat, location_lng,
 transfer_from, transfer_to, vehicle_info,
 meta_title_lv, meta_title_en, meta_title_es,
 meta_description_lv, meta_description_en, meta_description_es,
 is_active, sort_order
) VALUES
-- Excursions
('excursion','siguldas-pils-turaida','siguldas-pils-turaida','siguldas-pils-turaida',
 'Siguldas viduslaiku pils un Turaidas muzejrezervāts','Sigulda Medieval Castle and Turaida Museum Reserve','Castillo medieval de Sigulda y reserva museística de Turaida',
 'Divas Gaujas ielejas nozīmīgākās vietas vienā dienā — Livonijas ordeņa pilsdrupas un Turaidas sarkano ķieģeļu tornis.',
 'Two of the most important places in the Gauja valley in one day — the Livonian Order castle ruins and the red-brick Turaida tower.',
 'Dos de los lugares más importantes del valle del Gauja en un día: las ruinas de la Orden de Livonia y la torre de ladrillo rojo de Turaida.',
 E'Sākam Siguldas viduslaiku pilī, kuru 13. gadsimtā cēla Livonijas ordenis. Apstaigājam mūrus, uzkāpjam tornī un no skatu laukuma redzam visu Gaujas senleju.\n\nPēc tam dodamies uz Turaidas muzejrezervātu — 42 hektāru teritoriju ar sarkano ķieģeļu pili, baznīcu, Dainu kalnu un Turaidas Rozes kapu. Stāstu par Kaupo, par pils ugunsgrēku 1776. gadā un par to, kā tornis atkal tika atjaunots.\n\nMaršruts iet pa kājāmejamu teritoriju, tempu pielāgoju grupai. Ieejas biļetes objektos nav iekļautas cenā.',
 E'We start at Sigulda Medieval Castle, built by the Livonian Order in the 13th century. We walk the walls, climb the tower and take in the whole ancient Gauja valley from the viewing platform.\n\nThen we move to the Turaida Museum Reserve — 42 hectares with the red-brick castle, the church, Dainu Hill and the grave of the Rose of Turaida.\n\nThe route is walkable and the pace is adapted to the group. Entrance tickets are not included.',
 E'Comenzamos en el castillo medieval de Sigulda, construido por la Orden de Livonia en el siglo XIII. Recorremos los muros, subimos a la torre y contemplamos todo el valle antiguo del Gauja.\n\nDespués visitamos la reserva de Turaida: 42 hectáreas con el castillo de ladrillo rojo, la iglesia, la colina Dainu y la tumba de la Rosa de Turaida.\n\nEl ritmo se adapta al grupo. Las entradas no están incluidas.',
 240,45,true,2,8,ARRAY['history','culture']::public.enter_gauja_category[],NULL,'Sigulda',57.1626,24.8517,NULL,NULL,NULL,
 'Siguldas pils un Turaida — ekskursija ar gidi','Sigulda Castle and Turaida — guided tour','Castillo de Sigulda y Turaida — visita guiada',
 'Četru stundu ekskursija pa Siguldas viduslaiku pili un Turaidas muzejrezervātu ar sertificētu gidi.',
 'A four-hour guided tour of Sigulda Medieval Castle and the Turaida Museum Reserve with a certified guide.',
 'Excursión guiada de cuatro horas por el castillo medieval de Sigulda y la reserva de Turaida.',
 true,1),
('excursion','cesu-vecpilseta-pils','cesu-vecpilseta-pils','cesu-vecpilseta-pils',
 'Cēsu vecpilsēta un pils komplekss','Cēsis Old Town and Castle Complex','Casco antiguo de Cēsis y complejo del castillo',
 'Viduslaiku pilsdrupas ar tumšajiem pagrabiem, klusas bruģa ieliņas un vecpilsēta, ko var apstaigāt kājām.',
 'Medieval castle ruins with dark cellars, quiet cobbled streets and an old town you can walk end to end.',
 'Ruinas medievales con bodegas oscuras, calles empedradas y un casco antiguo que se recorre a pie.',
 E'Cēsis ir viena no retajām Latvijas pilsētām, kur viduslaiku plānojums saglabājies gandrīz nemainīgs. Sākam pils kompleksā — ar laternu ejam pa tumšajiem pagrabiem un kāpjam Rietumu tornī.\n\nTālāk pa vecpilsētu: Svētā Jāņa baznīca, Rožu laukums, Livonijas ordeņa mūri un amatnieku kvartāls. Stāstu par pilsētas lomu Hanzas tirdzniecībā un par 1577. gada notikumiem pilī.\n\nNoslēgumā — Cēsu pils parks. Maršruts pilnībā kājām, apmēram 3 km.',
 E'Cēsis is one of the few Latvian towns where the medieval layout survives almost unchanged. We start at the castle complex, walking the dark cellars with lanterns and climbing the Western Tower.\n\nThen the old town: St John''s Church, Rose Square, the Livonian Order walls and the craftsmen''s quarter.\n\nWe finish in the castle park. The route is entirely on foot, about 3 km.',
 E'Cēsis es una de las pocas ciudades letonas donde la traza medieval se conserva casi intacta. Empezamos en el castillo, recorriendo con farol las bodegas y subiendo a la Torre Oeste.\n\nLuego el casco antiguo: la iglesia de San Juan, la plaza de las Rosas y el barrio de artesanos.\n\nTerminamos en el parque del castillo. Unos 3 km a pie.',
 180,35,true,2,8,ARRAY['history','culture']::public.enter_gauja_category[],NULL,'Cēsis',57.3119,25.2749,NULL,NULL,NULL,
 'Cēsu vecpilsēta un pils — ekskursija','Cēsis Old Town and Castle — guided tour','Casco antiguo y castillo de Cēsis — visita',
 'Trīs stundu gājiens pa Cēsu viduslaiku pili un vecpilsētu sertificētas gides pavadībā.',
 'A three-hour walk through Cēsis medieval castle and old town with a certified guide.',
 'Paseo de tres horas por el castillo medieval y el casco antiguo de Cēsis con guía certificada.',
 true,2),
('excursion','ligatnes-ciemats-alas','ligatnes-ciemats-alas','ligatnes-ciemats-alas',
 'Līgatnes vēsturiskais ciemats un alu labirinti','Līgatne Historic Village and Cave Labyrinths','Aldea histórica de Līgatne y laberintos de cuevas',
 'Papīrfabrikas ciems ar alām smilšakmenī un meža takas Gaujas Nacionālā parka vidū.',
 'A paper mill village with sandstone cellars and forest trails in the middle of the Gauja National Park.',
 'Una aldea papelera con cuevas de arenisca y senderos en pleno Parque Nacional del Gauja.',
 E'Līgatne ir 19. gadsimta papīrfabrikas ciems, kas gandrīz nav mainījies: koka strādnieku mājas, meistaru villas, klubs un skola stāv tur, kur celtas.\n\nSmilšakmens kraujā izraktas alas — kādreiz pagrabi pārtikai, tagad viena no ciema zīmēm. Ejam gar tām, ieskatāmies un runājam par to, kā fabrika noteica visu dzīves ritmu.\n\nNoslēgumā nokāpjam pie Gaujas un, ja laiks atļauj, izmantojam vēsturisko prāmi.',
 E'Līgatne is a 19th-century paper mill village that has barely changed: wooden workers'' houses, foremen''s villas, the club and the school all stand where they were built.\n\nCaves dug into the sandstone cliff once served as food cellars and are now a symbol of the village.\n\nWe finish down by the Gauja and, weather permitting, use the historic cable ferry.',
 E'Līgatne es una aldea papelera del siglo XIX que apenas ha cambiado: casas de madera de los obreros, villas de los capataces, el club y la escuela.\n\nLas cuevas excavadas en la arenisca fueron despensas y hoy son el emblema del pueblo.\n\nTerminamos junto al Gauja y, si el tiempo lo permite, usamos el ferry histórico.',
 180,30,true,2,8,ARRAY['history','nature']::public.enter_gauja_category[],NULL,'Līgatne',57.2333,25.0500,NULL,NULL,NULL,
 'Līgatnes ciemats un alas — ekskursija','Līgatne village and caves — guided tour','Aldea de Līgatne y cuevas — visita',
 'Trīs stundu ekskursija pa Līgatnes papīrfabrikas ciematu, smilšakmens alām un Gaujas krastu.',
 'A three-hour guided tour of the Līgatne paper mill village, sandstone caves and the Gauja riverside.',
 'Excursión de tres horas por la aldea papelera de Līgatne, las cuevas de arenisca y la orilla del Gauja.',
 true,3),
('excursion','gaujas-nacionalais-parks','gaujas-nacionalais-parks','gaujas-nacionalais-parks',
 'Gaujas Nacionālais parks — dabas skaistums un vēsture','Gauja National Park — Nature and History','Parque Nacional del Gauja — naturaleza e historia',
 'Pilna diena parkā: smilšakmens klintis, senleja, pilis un skatu vietas vienā maršrutā.',
 'A full day in the park: sandstone cliffs, the ancient valley, castles and viewpoints in one route.',
 'Un día completo en el parque: acantilados de arenisca, el valle antiguo, castillos y miradores.',
 E'Sešu stundu maršruts pa Latvijas vecāko nacionālo parku. Sākam ar senlejas skatu vietām, tad ejam pie smilšakmens atsegumiem — Gūtmaņa alas, Velnalas un mazāk zināmām klintīm.\n\nDienas otrajā pusē pievēršamies vēsturei: pilsdrupas, muižas un stāsti par Gaujas lībiešiem.\n\nMaršrutu pielāgoju sezonai un laikapstākļiem. Ērti apavi obligāti, līdzi ņemam ūdeni un uzkodas.',
 E'A six-hour route through Latvia''s oldest national park. We start with valley viewpoints, then visit the sandstone outcrops — Gūtmanis Cave, Velnala and lesser-known cliffs.\n\nIn the afternoon we turn to history: castle ruins, manors and the story of the Gauja Livonians.\n\nThe route is adapted to the season. Sturdy shoes required.',
 E'Ruta de seis horas por el parque nacional más antiguo de Letonia: miradores, afloramientos de arenisca, la cueva de Gūtmanis y acantilados menos conocidos.\n\nPor la tarde, historia: ruinas, mansiones y los livonios del Gauja.\n\nLa ruta se adapta a la estación. Calzado adecuado imprescindible.',
 360,65,true,2,8,ARRAY['nature','history']::public.enter_gauja_category[],NULL,'Gaujas Nacionālais parks',57.2500,25.0000,NULL,NULL,NULL,
 'Gaujas Nacionālais parks — pilnas dienas ekskursija','Gauja National Park — full day guided tour','Parque Nacional del Gauja — excursión de día completo',
 'Sešu stundu ekskursija pa Gaujas Nacionālo parku: klintis, senleja, pilis un skatu vietas.',
 'A six-hour guided tour of the Gauja National Park: cliffs, the ancient valley, castles and viewpoints.',
 'Excursión de seis horas por el Parque Nacional del Gauja: acantilados, valle, castillos y miradores.',
 true,4),
('excursion','krimuldas-muiza','krimuldas-muiza','krimuldas-muiza',
 'Krimuldas baznīca, muiža un Gaujas ainavas','Krimulda Church, Manor and Gauja Views','Iglesia y mansión de Krimulda y paisajes del Gauja',
 'Klusākā Gaujas senlejas puse: 13. gadsimta baznīca, klasicisma muiža un skats pāri ielejai.',
 'The quieter side of the Gauja valley: a 13th-century church, a classicist manor and views across the valley.',
 'El lado tranquilo del valle: una iglesia del siglo XIII, una mansión neoclásica y vistas al valle.',
 E'Krimulda ir Siguldas pretējā Gaujas krastā, un tur ir ievērojami klusāk. Sākam pie Krimuldas baznīcas, vienas no vecākajām Latvijā, kuras pirmsākumi meklējami 13. gadsimtā.\n\nTālāk ejam uz Krimuldas muižu — klasicisma ēku ar parku un skatu uz senleju. Stāstu par Lievenu dzimtu un par to, kā muiža kļuva par sanatoriju.\n\nNoslēgumā pastaiga līdz skatu vietām un, ja vēlaties, nobrauciens ar gaisa trošu vagoniņu (nav iekļauts cenā).',
 E'Krimulda lies on the opposite bank from Sigulda and is noticeably quieter. We start at Krimulda Church, one of the oldest in Latvia, with 13th-century origins.\n\nThen the classicist Krimulda Manor with its park and valley views, and the story of the Lieven family.\n\nWe finish at the viewpoints; the cable car ride is optional and not included.',
 E'Krimulda está en la orilla opuesta a Sigulda y es mucho más tranquila. Empezamos en la iglesia, una de las más antiguas de Letonia.\n\nSeguimos con la mansión neoclásica, su parque y las vistas al valle, y la historia de la familia Lieven.\n\nTerminamos en los miradores; el teleférico es opcional.',
 180,30,true,2,8,ARRAY['history','nature']::public.enter_gauja_category[],NULL,'Krimulda',57.1833,24.8333,NULL,NULL,NULL,
 'Krimuldas muiža un baznīca — ekskursija','Krimulda Manor and Church — guided tour','Mansión e iglesia de Krimulda — visita',
 'Trīs stundu ekskursija Krimuldā: viduslaiku baznīca, klasicisma muiža un Gaujas senlejas skati.',
 'A three-hour guided tour in Krimulda: medieval church, classicist manor and Gauja valley views.',
 'Excursión de tres horas en Krimulda: iglesia medieval, mansión neoclásica y vistas del valle.',
 true,5),
('excursion','araisu-ezerpils','araisu-ezerpils','araisu-ezerpils',
 'Āraišu ezerpils un arheoloģiskais parks','Āraiši Lake Fortress and Archaeological Park','Fortaleza lacustre de Āraiši y parque arqueológico',
 'Rekonstruēta 9. gadsimta latgaļu apmetne uz salas un akmens laikmeta mājokļi krastā.',
 'A reconstructed 9th-century Latgalian settlement on an island, with Stone Age dwellings on the shore.',
 'Un asentamiento letgalio del siglo IX reconstruido sobre una isla y viviendas de la Edad de Piedra.',
 E'Āraišu ezerpils ir viena no retajām vietām Eiropā, kur uz ezera salas rekonstruēta 9. gadsimta apmetne tieši tur, kur to atrada arheologi.\n\nEjam pa koka celiņiem starp mājām, skatāmies, kā cilvēki dzīvoja pirms tūkstoš gadiem, un runājam par izrakumiem, kas ilga vairākus gadu desmitus.\n\nKrastā apskatām akmens un bronzas laikmeta mājokļu rekonstrukcijas, viduslaiku pilsdrupas un Āraišu vējdzirnavas.',
 E'Āraiši Lake Fortress is one of the few places in Europe where a 9th-century settlement has been reconstructed on the very island where archaeologists found it.\n\nWe walk the wooden paths between the houses and talk about excavations that lasted decades.\n\nOn the shore we see Stone and Bronze Age reconstructions, the medieval castle ruins and the Āraiši windmill.',
 E'La fortaleza lacustre de Āraiši es uno de los pocos lugares de Europa donde se ha reconstruido un asentamiento del siglo IX en la misma isla donde fue hallado.\n\nRecorremos las pasarelas de madera y hablamos de las excavaciones.\n\nEn la orilla vemos reconstrucciones prehistóricas, las ruinas medievales y el molino de Āraiši.',
 240,40,true,2,8,ARRAY['history','culture']::public.enter_gauja_category[],NULL,'Āraiši',57.2500,25.2833,NULL,NULL,NULL,
 'Āraišu ezerpils — ekskursija ar gidi','Āraiši Lake Fortress — guided tour','Fortaleza lacustre de Āraiši — visita guiada',
 'Četru stundu ekskursija uz Āraišu ezerpili un arheoloģisko parku ar sertificētu gidi.',
 'A four-hour guided tour of the Āraiši Lake Fortress and archaeological park.',
 'Excursión de cuatro horas a la fortaleza lacustre de Āraiši y su parque arqueológico.',
 true,6),
('excursion','zvartes-iezis-amata','zvartes-iezis-amata','zvartes-iezis-amata',
 'Zvārtes iezis un Amatas upes ainavas','Zvārte Rock and the Amata River Landscape','Roca de Zvārte y paisajes del río Amata',
 'Viens no atpazīstamākajiem Latvijas smilšakmens iežiem un taka gar Amatas krastiem.',
 'One of Latvia''s most recognisable sandstone cliffs and a trail along the Amata river.',
 'Uno de los acantilados de arenisca más conocidos de Letonia y un sendero junto al Amata.',
 E'Zvārtes iezis ir 20 metrus augsta smilšakmens klints Amatas upes līkumā — vieta, kur ainava mainās ik pēc dažiem soļiem.\n\nEjam pa taku gar upi, apstājamies pie atsegumiem un runājam par to, kā devona smilšakmens veidojies 350 miljonu gadu laikā, un par teikām, kas ar iezi saistītas.\n\nMaršruts ir daļēji nelīdzens, ar kāpumiem un koka kāpnēm. Ērti apavi nepieciešami.',
 E'Zvārte Rock is a 20-metre sandstone cliff in a bend of the Amata river, where the landscape changes every few steps.\n\nWe follow the riverside trail, stop at the outcrops and talk about Devonian sandstone formed over 350 million years — and the legends attached to the cliff.\n\nThe trail is uneven in places, with climbs and wooden stairs.',
 E'La roca de Zvārte es un acantilado de arenisca de 20 metros en un meandro del Amata.\n\nSeguimos el sendero junto al río, paramos en los afloramientos y hablamos de la arenisca devónica y de las leyendas del lugar.\n\nEl sendero es irregular en tramos, con escaleras de madera.',
 240,40,true,2,8,ARRAY['nature','action']::public.enter_gauja_category[],NULL,'Amata',57.2167,25.1000,NULL,NULL,NULL,
 'Zvārtes iezis un Amata — ekskursija','Zvārte Rock and Amata — guided tour','Roca de Zvārte y Amata — visita guiada',
 'Četru stundu ekskursija pie Zvārtes ieža un pa Amatas upes taku ar gidi.',
 'A four-hour guided tour to Zvārte Rock and along the Amata river trail.',
 'Excursión de cuatro horas a la roca de Zvārte y por el sendero del río Amata.',
 true,7),
-- Hikes
('hiking','gimenes-pargajiens-turaida','gimenes-pargajiens-turaida','gimenes-pargajiens-turaida',
 'Ģimenes pārgājiens Turaidas apkaimē','Family Hike around Turaida','Caminata familiar por los alrededores de Turaida',
 'Viegls maršruts ar bērniem pa mežu takām, avotiem un skatu vietām pie Turaidas.',
 'An easy family route along forest trails, springs and viewpoints near Turaida.',
 'Ruta fácil para familias por senderos, manantiales y miradores cerca de Turaida.',
 E'Maršruts domāts ģimenēm ar bērniem no aptuveni piecu gadu vecuma. Ejam pa mežu takām Turaidas apkaimē, apstājamies pie avotiem un skatu vietām.\n\nPa ceļam runājam par mežu, kokiem un dzīvniekiem tā, lai bērniem ir interesanti: kāpēc priede aug tieši šeit, kā pēc pēdām saprast, kurš ceļu šķērsojis.\n\nTempu nosaka jaunākais dalībnieks. Pārtraukumi tik bieži, cik nepieciešams.',
 E'A route for families with children from around five years old. We walk forest trails around Turaida, stopping at springs and viewpoints.\n\nAlong the way we talk about the forest in a way children enjoy: why a pine grows here, how to read animal tracks.\n\nThe youngest participant sets the pace.',
 E'Ruta para familias con niños desde unos cinco años, por senderos forestales cerca de Turaida.\n\nHablamos del bosque de forma amena: por qué crece aquí ese pino, cómo leer huellas de animales.\n\nEl ritmo lo marca el más pequeño.',
 180,25,true,2,10,ARRAY['nature']::public.enter_gauja_category[],'easy','Turaida',57.1833,24.8500,NULL,NULL,NULL,
 'Ģimenes pārgājiens Turaidā','Family hike in Turaida','Caminata familiar en Turaida',
 'Viegls trīs stundu ģimenes pārgājiens Turaidas mežos ar sertificētu gidi.',
 'An easy three-hour family hike in the Turaida forests with a certified guide.',
 'Caminata familiar fácil de tres horas por los bosques de Turaida con guía certificada.',
 true,8),
('hiking','sigulda-krimulda-pargajiens','sigulda-krimulda-pargajiens','sigulda-krimulda-pargajiens',
 'Gaujas krastu pārgājiens Sigulda–Krimulda','Sigulda–Krimulda Riverside Hike','Caminata Sigulda–Krimulda por la orilla del Gauja',
 'Klasisks senlejas maršruts abos Gaujas krastos ar kāpumiem, alām un tiltu.',
 'The classic valley route on both banks of the Gauja, with climbs, caves and the bridge.',
 'La ruta clásica del valle por ambas orillas, con desniveles, cuevas y el puente.',
 E'Maršruts sākas Siguldā, nolaižas senlejā, šķērso Gauju un kāpj augšā Krimuldas pusē. Kopā apmēram 9 km ar vairākiem kāpumiem.\n\nPa ceļam — Gūtmaņa ala ar avotu, smilšakmens atsegumi, skatu vietas un vecās kāpnes. Stāstu par senlejas veidošanos un par lībiešu laika apmetnēm abos krastos.\n\nNepieciešami ērti apavi un ūdens. Maršruts nav piemērots ratiņiem.',
 E'The route starts in Sigulda, drops into the valley, crosses the Gauja and climbs the Krimulda side — about 9 km with several ascents.\n\nAlong the way: Gūtmanis Cave and its spring, sandstone outcrops, viewpoints and the old stairways.\n\nSturdy shoes and water needed; not suitable for pushchairs.',
 E'La ruta parte de Sigulda, baja al valle, cruza el Gauja y sube por Krimulda: unos 9 km con varios ascensos.\n\nPor el camino: la cueva de Gūtmanis, afloramientos de arenisca y miradores.\n\nSe necesita calzado adecuado y agua.',
 240,30,true,2,10,ARRAY['nature','action']::public.enter_gauja_category[],'medium','Sigulda',57.1626,24.8517,NULL,NULL,NULL,
 'Pārgājiens Sigulda–Krimulda','Sigulda–Krimulda hike','Caminata Sigulda–Krimulda',
 'Vidējas grūtības 9 km pārgājiens pa Gaujas senleju no Siguldas uz Krimuldu.',
 'A moderate 9 km hike through the Gauja valley from Sigulda to Krimulda.',
 'Caminata moderada de 9 km por el valle del Gauja, de Sigulda a Krimulda.',
 true,9),
('hiking','zvartes-amata-pargajiens','zvartes-amata-pargajiens','zvartes-amata-pargajiens',
 'Zvārtes ieža un Amatas krastu pārgājiens','Zvārte Rock and Amata Riverside Hike','Caminata por la roca de Zvārte y el Amata',
 'Piecas stundas gar Amatas upi: iezis, straujteces un meža takas bez pūļa.',
 'Five hours along the Amata: the cliff, rapids and forest trails without the crowds.',
 'Cinco horas junto al Amata: el acantilado, rápidos y senderos sin multitudes.',
 E'Amatas taka ir viens no skaistākajiem maršrutiem Gaujas Nacionālajā parkā, īpaši pavasarī un rudenī. Ejam gar upi, kur straume ir ātra un krasti stāvi.\n\nGalvenais punkts — Zvārtes iezis, bet ceļā ir vēl vairāki mazāk zināmi atsegumi un pārbrišanas vietas.\n\nMaršruts vidējas grūtības, apmēram 10 km, ar nelīdzenu segumu. Nepieciešami stingri apavi.',
 E'The Amata trail is one of the finest routes in the Gauja National Park, especially in spring and autumn, following a fast river between steep banks.\n\nThe highlight is Zvārte Rock, but there are several lesser-known outcrops and fords on the way.\n\nModerate, about 10 km on uneven ground. Firm footwear required.',
 E'El sendero del Amata es de los más bellos del parque, sobre todo en primavera y otoño, junto a un río rápido entre orillas escarpadas.\n\nEl punto principal es la roca de Zvārte, con otros afloramientos y vados en el camino.\n\nDificultad media, unos 10 km.',
 300,35,true,2,10,ARRAY['nature','action']::public.enter_gauja_category[],'medium','Amata',57.2167,25.1000,NULL,NULL,NULL,
 'Amatas takas pārgājiens ar gidi','Amata trail guided hike','Caminata guiada por el sendero del Amata',
 'Piecu stundu pārgājiens pa Amatas taku līdz Zvārtes iezim sertificētas gides pavadībā.',
 'A five-hour guided hike along the Amata trail to Zvārte Rock.',
 'Caminata guiada de cinco horas por el sendero del Amata hasta la roca de Zvārte.',
 true,10),
('hiking','ligatnes-dabas-takas','ligatnes-dabas-takas','ligatnes-dabas-takas',
 'Līgatnes dabas takas — pilna diena','Līgatne Nature Trails — Full Day','Senderos naturales de Līgatne — día completo',
 'Sešas stundas mežā: dabas takas, savvaļas dzīvnieku aploki un Gaujas krasts.',
 'Six hours in the forest: nature trails, wildlife enclosures and the Gauja riverside.',
 'Seis horas en el bosque: senderos, recintos de fauna y la orilla del Gauja.',
 E'Līgatnes dabas takas ir plaša mežu teritorija ar takām, skatu torņiem un aplokiem, kur redzami Latvijas savvaļas dzīvnieki — aļņi, staltbrieži, lūši, lapsas.\n\nDienas laikā izejam garo loku, apstājamies pie aplokiem un skatu torņa, un noslēgumā nokāpjam pie Gaujas.\n\nMaršruts garš, bet bez smagiem kāpumiem. Līdzi ņemam pusdienas un ūdeni.',
 E'The Līgatne nature trails cover a large forest area with paths, viewing towers and enclosures where Latvian wildlife can be seen — elk, red deer, lynx, foxes.\n\nWe walk the long loop, stop at the enclosures and the tower, and finish by the Gauja.\n\nLong but without hard climbs. Bring lunch and water.',
 E'Los senderos de Līgatne recorren un gran bosque con torres de observación y recintos con fauna letona: alces, ciervos, linces, zorros.\n\nHacemos el circuito largo y terminamos junto al Gauja.\n\nLargo pero sin ascensos duros. Traer comida y agua.',
 360,45,true,2,10,ARRAY['nature']::public.enter_gauja_category[],'medium','Līgatne',57.2333,25.0500,NULL,NULL,NULL,
 'Līgatnes dabas takas — pilnas dienas pārgājiens','Līgatne nature trails — full day hike','Senderos de Līgatne — caminata de día completo',
 'Sešu stundu pārgājiens pa Līgatnes dabas takām ar savvaļas dzīvnieku aplokiem.',
 'A six-hour hike along the Līgatne nature trails with wildlife enclosures.',
 'Caminata de seis horas por los senderos de Līgatne con recintos de fauna.',
 true,11),
('hiking','cesu-mezi-ezeri','cesu-mezi-ezeri','cesu-mezi-ezeri',
 'Cēsu apkaimes meži un ezeri','Forests and Lakes around Cēsis','Bosques y lagos de los alrededores de Cēsis',
 'Mierīgs maršruts pa priežu mežiem un ezeru krastiem netālu no Cēsīm.',
 'A calm route through pine forests and along lake shores near Cēsis.',
 'Ruta tranquila por pinares y orillas de lagos cerca de Cēsis.',
 E'Ap Cēsīm ir vairāki nelieli ezeri, pie kuriem tūristi nonāk reti. Ejam pa priežu mežu takām, apstājamies pie Cīrulīšu dabas takām un ezera krasta.\n\nMaršruts viegls, bez stāviem kāpumiem, piemērots arī tiem, kas pārgājienos iet reti.\n\nVasarā iespējama peldēšanās, rudenī — sēņošana un ogošana.',
 E'There are several small lakes around Cēsis that tourists rarely reach. We walk pine forest trails, stopping at the Cīrulīši nature trails and the lake shore.\n\nEasy, with no steep climbs — suitable for occasional walkers.\n\nSwimming in summer, mushroom and berry picking in autumn.',
 E'Cerca de Cēsis hay varios lagos poco visitados. Caminamos por pinares y paramos en los senderos de Cīrulīši y en la orilla.\n\nFácil, sin ascensos pronunciados.\n\nEn verano se puede nadar; en otoño, recoger setas.',
 240,30,true,2,10,ARRAY['nature']::public.enter_gauja_category[],'easy','Cēsis',57.3119,25.2749,NULL,NULL,NULL,
 'Pārgājiens Cēsu mežos un pie ezeriem','Hike in the forests and lakes of Cēsis','Caminata por bosques y lagos de Cēsis',
 'Viegls četru stundu pārgājiens pa Cēsu apkaimes priežu mežiem un ezeru krastiem.',
 'An easy four-hour hike through pine forests and lake shores around Cēsis.',
 'Caminata fácil de cuatro horas por pinares y lagos cerca de Cēsis.',
 true,12),
('hiking','gaujas-np-dienas-marsruts','gaujas-np-dienas-marsruts','gaujas-np-dienas-marsruts',
 'Gaujas NP dienas maršruts','Gauja NP Full-Day Route','Ruta de día completo por el Parque Nacional',
 'Astoņas stundas un ap 20 km pa mazāk zināmām parka takām pieredzējušiem gājējiem.',
 'Eight hours and about 20 km on the park''s lesser-known trails, for experienced walkers.',
 'Ocho horas y unos 20 km por senderos poco conocidos, para caminantes experimentados.',
 E'Garākais maršruts manā piedāvājumā — apmēram 20 km pa Gaujas Nacionālā parka takām, kuras nav norādītas standarta kartēs.\n\nEjam pa senlejas malām, meža ceļiem un upju krastiem, ar vairākiem kāpumiem un nolaišanās posmiem. Apstāšanās pie atsegumiem un skatu vietām.\n\nPiemērots tikai tiem, kas regulāri staigā. Nepieciešami pārgājienu apavi, ūdens vismaz 1,5 l un pusdienas līdzi.',
 E'The longest route I offer — about 20 km on Gauja National Park trails that are not on standard maps.\n\nWe follow valley edges, forest roads and riverbanks, with several ascents and descents, stopping at outcrops and viewpoints.\n\nOnly for regular walkers. Hiking boots, at least 1.5 l of water and a packed lunch required.',
 E'La ruta más larga que ofrezco: unos 20 km por senderos que no aparecen en los mapas habituales.\n\nBordes del valle, caminos forestales y orillas, con varios desniveles.\n\nSolo para caminantes habituales. Botas, 1,5 l de agua y comida.',
 480,60,true,2,10,ARRAY['nature','action']::public.enter_gauja_category[],'hard','Gaujas Nacionālais parks',57.2500,25.0000,NULL,NULL,NULL,
 'Gaujas NP dienas pārgājiens','Gauja NP full-day hike','Caminata de día completo en el Parque del Gauja',
 'Astoņu stundu, 20 km pārgājiens pa Gaujas Nacionālā parka mazāk zināmajām takām.',
 'An eight-hour, 20 km hike on the lesser-known trails of the Gauja National Park.',
 'Caminata de ocho horas y 20 km por los senderos menos conocidos del parque.',
 true,13),
('hiking','vakara-pargajiens-saulriets','vakara-pargajiens-saulriets','vakara-pargajiens-saulriets',
 'Vakara pārgājiens ar saulrieta izbaudīšanu','Evening Hike with Sunset','Caminata vespertina con puesta de sol',
 'Trīs stundas vakara gaismā līdz skatu vietai, kur saule noriet pāri senlejai.',
 'Three hours in evening light to a viewpoint where the sun sets over the valley.',
 'Tres horas con luz vespertina hasta un mirador sobre el valle.',
 E'Izejam pāris stundas pirms saulrieta un ejam mierīgā tempā uz skatu vietu senlejas malā.\n\nVakarā mežs skan citādi, gaisma maina ainavu ik pēc dažām minūtēm, un cilvēku takās gandrīz nav. Pa ceļam runājam par vietas stāstiem un vakara dabu.\n\nLīdzi ņemam siltāku jaku un lukturīti atpakaļceļam. Maršruts viegls.',
 E'We set out a couple of hours before sunset and walk at a calm pace to a viewpoint on the edge of the valley.\n\nThe forest sounds different in the evening, the light changes the landscape every few minutes and the trails are almost empty.\n\nBring a warm jacket and a torch for the way back. Easy route.',
 E'Salimos un par de horas antes del atardecer hacia un mirador en el borde del valle.\n\nEl bosque suena distinto al anochecer y los senderos están casi vacíos.\n\nLleve chaqueta y linterna. Ruta fácil.',
 180,30,true,2,10,ARRAY['nature','culture']::public.enter_gauja_category[],'easy','Sigulda',57.1626,24.8517,NULL,NULL,NULL,
 'Vakara pārgājiens ar saulrietu Siguldā','Evening sunset hike in Sigulda','Caminata al atardecer en Sigulda',
 'Viegls trīs stundu vakara pārgājiens ar saulrietu Gaujas senlejas skatu vietā.',
 'An easy three-hour evening hike with sunset over the Gauja valley.',
 'Caminata fácil de tres horas al atardecer sobre el valle del Gauja.',
 true,14),
-- Transfers
('transfer','transfers-riga-sigulda','transfers-riga-sigulda','transfers-riga-sigulda',
 'Transfērs Rīga — Sigulda','Transfer Riga — Sigulda','Traslado Riga — Sigulda',
 'Privāts brauciens no Rīgas uz Siguldu ērtā automašīnā, līdz četriem pasažieriem.',
 'A private ride from Riga to Sigulda in a comfortable car, up to four passengers.',
 'Traslado privado de Riga a Sigulda en coche cómodo, hasta cuatro pasajeros.',
 E'Privāts transfērs no jebkuras adreses Rīgā uz Siguldu. Brauciens ilgst apmēram stundu.\n\nAutomašīna Volvo XC60 — vieta četriem pasažieriem un bagāžai. Laiku saskaņojam iepriekš, gaidīšana norunātajā vietā ir iekļauta.\n\nCena ir par braucienu, nevis par personu. Ja vēlaties, pa ceļam varu īsi pastāstīt par vietām, kurām braucam garām.',
 E'A private transfer from any address in Riga to Sigulda, about an hour''s drive.\n\nVolvo XC60 with room for four passengers and luggage. Time is agreed in advance and waiting at the pick-up point is included.\n\nThe price is per ride, not per person.',
 E'Traslado privado desde cualquier dirección de Riga a Sigulda, aproximadamente una hora.\n\nVolvo XC60 con sitio para cuatro pasajeros y equipaje. La espera está incluida.\n\nEl precio es por trayecto, no por persona.',
 60,60,false,1,4,ARRAY['getaround']::public.enter_gauja_category[],NULL,'Sigulda',57.1626,24.8517,'Rīga','Sigulda','Volvo XC60, 1–4 personas',
 'Transfērs Rīga — Sigulda','Private transfer Riga — Sigulda','Traslado privado Riga — Sigulda',
 'Privāts transfērs no Rīgas uz Siguldu ar Volvo XC60, līdz četrām personām, cena par braucienu.',
 'Private transfer from Riga to Sigulda in a Volvo XC60, up to four people, price per ride.',
 'Traslado privado de Riga a Sigulda en Volvo XC60, hasta cuatro personas, precio por trayecto.',
 true,15),
('transfer','transfers-lidosta-sigulda','transfers-lidosta-sigulda','transfers-lidosta-sigulda',
 'Transfērs Rīgas lidosta — Sigulda / Cēsis','Transfer Riga Airport — Sigulda / Cēsis','Traslado aeropuerto de Riga — Sigulda / Cēsis',
 'Sagaidīšana lidostā ar zīmi un brauciens tieši uz naktsmītni Siguldā vai Cēsīs.',
 'Meet and greet at the airport and a direct ride to your accommodation in Sigulda or Cēsis.',
 'Recepción en el aeropuerto y traslado directo a su alojamiento en Sigulda o Cēsis.',
 E'Sagaidu lidostas ierašanās zālē ar zīmi un palīdzu ar bagāžu. Lidojuma numuru lūdzu norādīt rezervācijā — ja lidojums kavējas, gaidīšana ir bez papildu maksas.\n\nBrauciens uz Siguldu ilgst apmēram 1 h 15 min, uz Cēsīm — apmēram 1 h 45 min.\n\nAutomašīna Volvo XC60, četras vietas. Cena par braucienu.',
 E'I meet you in the arrivals hall with a sign and help with luggage. Please give your flight number when booking — if the flight is delayed, waiting is free of charge.\n\nAbout 1 h 15 min to Sigulda, about 1 h 45 min to Cēsis.\n\nVolvo XC60, four seats. Price per ride.',
 E'Le recibo en la sala de llegadas con un cartel y ayudo con el equipaje. Indique su número de vuelo al reservar; si se retrasa, la espera es gratuita.\n\nUnos 1 h 15 min a Sigulda y 1 h 45 min a Cēsis.\n\nVolvo XC60, cuatro plazas.',
 105,70,false,1,4,ARRAY['getaround']::public.enter_gauja_category[],NULL,'Rīgas lidosta',56.9236,23.9711,'Rīgas lidosta (RIX)','Sigulda / Cēsis','Volvo XC60, 1–4 personas',
 'Transfērs no Rīgas lidostas uz Siguldu vai Cēsīm','Riga Airport transfer to Sigulda or Cēsis','Traslado desde el aeropuerto de Riga a Sigulda o Cēsis',
 'Privāts transfērs no Rīgas lidostas uz Siguldu vai Cēsīm ar sagaidīšanu un bagāžas palīdzību.',
 'Private transfer from Riga Airport to Sigulda or Cēsis with meet and greet.',
 'Traslado privado desde el aeropuerto de Riga a Sigulda o Cēsis con recepción.',
 true,16),
('transfer','transfers-riga-cesis','transfers-riga-cesis','transfers-riga-cesis',
 'Transfērs Rīga — Cēsis / Līgatne','Transfer Riga — Cēsis / Līgatne','Traslado Riga — Cēsis / Līgatne',
 'Brauciens uz Cēsīm vai Līgatni ar iespēju pieturēt skatu vietā pa ceļam.',
 'A ride to Cēsis or Līgatne with the option of a viewpoint stop on the way.',
 'Traslado a Cēsis o Līgatne con posibilidad de parar en un mirador.',
 E'Privāts transfērs no Rīgas uz Cēsīm vai Līgatni. Brauciens ilgst apmēram pusotru stundu.\n\nJa vēlaties, pa ceļam varam apstāties vienā skatu vietā vai pie Līgatnes prāmja — par to vienojamies iepriekš.\n\nAutomašīna Volvo XC60, līdz četrām personām un bagāžai. Cena par braucienu.',
 E'Private transfer from Riga to Cēsis or Līgatne, about an hour and a half.\n\nIf you wish, we can stop at one viewpoint or at the Līgatne ferry — agreed in advance.\n\nVolvo XC60, up to four people with luggage. Price per ride.',
 E'Traslado privado de Riga a Cēsis o Līgatne, aproximadamente hora y media.\n\nSi lo desea, podemos parar en un mirador o en el ferry de Līgatne.\n\nVolvo XC60, hasta cuatro personas.',
 100,80,false,1,4,ARRAY['getaround']::public.enter_gauja_category[],NULL,'Cēsis',57.3119,25.2749,'Rīga','Cēsis / Līgatne','Volvo XC60, 1–4 personas',
 'Transfērs Rīga — Cēsis un Līgatne','Private transfer Riga — Cēsis and Līgatne','Traslado privado Riga — Cēsis y Līgatne',
 'Privāts transfērs no Rīgas uz Cēsīm vai Līgatni ar Volvo XC60, cena par braucienu.',
 'Private transfer from Riga to Cēsis or Līgatne in a Volvo XC60, price per ride.',
 'Traslado privado de Riga a Cēsis o Līgatne en Volvo XC60, precio por trayecto.',
 true,17),
('transfer','transfers-jurmala-sigulda','transfers-jurmala-sigulda','transfers-jurmala-sigulda',
 'Transfērs Jūrmala — Sigulda','Transfer Jūrmala — Sigulda','Traslado Jūrmala — Sigulda',
 'No jūras uz Gaujas senleju bez pārsēšanās — tiešs brauciens no Jūrmalas.',
 'From the sea to the Gauja valley without changing transport — a direct ride from Jūrmala.',
 'Del mar al valle del Gauja sin transbordos: traslado directo desde Jūrmala.',
 E'Privāts transfērs no jebkuras adreses Jūrmalā uz Siguldu. Brauciens ilgst apmēram pusotru stundu, apbraucot Rīgu.\n\nĒrts risinājums, ja atpūšaties pie jūras, bet vienu dienu vēlaties pavadīt Gaujas ielejā. Atpakaļceļu varam saskaņot uzreiz.\n\nAutomašīna Volvo XC60, četras vietas. Cena par braucienu.',
 E'Private transfer from any address in Jūrmala to Sigulda, about an hour and a half, bypassing Riga.\n\nA convenient option if you are staying by the sea but want to spend a day in the Gauja valley. The return trip can be arranged at the same time.\n\nVolvo XC60, four seats.',
 E'Traslado privado desde cualquier dirección de Jūrmala a Sigulda, hora y media, rodeando Riga.\n\nCómodo si se aloja junto al mar y quiere pasar un día en el valle del Gauja.\n\nVolvo XC60, cuatro plazas.',
 90,70,false,1,4,ARRAY['getaround']::public.enter_gauja_category[],NULL,'Jūrmala',56.9680,23.7700,'Jūrmala','Sigulda','Volvo XC60, 1–4 personas',
 'Transfērs Jūrmala — Sigulda','Private transfer Jūrmala — Sigulda','Traslado privado Jūrmala — Sigulda',
 'Privāts transfērs no Jūrmalas uz Siguldu ar Volvo XC60, līdz četrām personām.',
 'Private transfer from Jūrmala to Sigulda in a Volvo XC60, up to four people.',
 'Traslado privado de Jūrmala a Sigulda en Volvo XC60, hasta cuatro personas.',
 true,18),
('transfer','transfers-riga-kemeri','transfers-riga-kemeri','transfers-riga-kemeri',
 'Transfērs Rīga — Ķemeru Nacionālais parks','Transfer Riga — Ķemeri National Park','Traslado Riga — Parque Nacional de Ķemeri',
 'Brauciens uz purva laipām un Ķemeru parku ar gaidīšanu uz vietas.',
 'A ride to the bog boardwalks and Ķemeri park, with waiting on site.',
 'Traslado a las pasarelas del pantano de Ķemeri, con espera incluida.',
 E'Privāts transfērs no Rīgas uz Ķemeru Nacionālo parku — vietu, kur pa koka laipām var izstaigāt Lielo Ķemeru tīreli.\n\nBrauciens ilgst apmēram stundu. Varu jūs nogādāt pie laipu sākuma un sagaidīt pēc pastaigas, vai arī atgriezties norunātā laikā.\n\nAutomašīna Volvo XC60, līdz četrām personām. Cena par braucienu vienā virzienā.',
 E'Private transfer from Riga to Ķemeri National Park, where wooden boardwalks cross the Great Ķemeri Bog.\n\nAbout an hour''s drive. I can drop you at the boardwalk entrance and wait, or return at an agreed time.\n\nVolvo XC60, up to four people. Price per one-way ride.',
 E'Traslado privado de Riga al Parque Nacional de Ķemeri, con pasarelas de madera sobre la turbera.\n\nUna hora de trayecto. Puedo esperarle o volver a la hora acordada.\n\nVolvo XC60, hasta cuatro personas.',
 60,65,false,1,4,ARRAY['getaround']::public.enter_gauja_category[],NULL,'Ķemeru Nacionālais parks',56.9470,23.5000,'Rīga','Ķemeru Nacionālais parks','Volvo XC60, 1–4 personas',
 'Transfērs Rīga — Ķemeru Nacionālais parks','Private transfer Riga — Ķemeri National Park','Traslado privado Riga — Parque de Ķemeri',
 'Privāts transfērs no Rīgas uz Ķemeru Nacionālo parku un purva laipām.',
 'Private transfer from Riga to Ķemeri National Park and the bog boardwalks.',
 'Traslado privado de Riga al Parque Nacional de Ķemeri y sus pasarelas.',
 true,19),
('transfer','transfers-baltijas-pilsetas','transfers-baltijas-pilsetas','transfers-baltijas-pilsetas',
 'Baltijas pilsētu transfērs','Baltic Cities Transfer','Traslado entre capitales bálticas',
 'Garais brauciens no Rīgas uz Tallinu vai Viļņu ar pieturām pēc vienošanās.',
 'The long ride from Riga to Tallinn or Vilnius, with stops by arrangement.',
 'El trayecto largo de Riga a Tallin o Vilna, con paradas acordadas.',
 E'Privāts transfērs no Rīgas uz Tallinu vai Viļņu. Brauciens ilgst apmēram četras stundas katrā virzienā.\n\nPa ceļam varam ieplānot vienu vai divas pieturas — piemēram, Pērnavā vai Rundālē. Par maršrutu vienojamies iepriekš.\n\nAutomašīna Volvo XC60, līdz četrām personām ar bagāžu. Cena par braucienu vienā virzienā.',
 E'Private transfer from Riga to Tallinn or Vilnius, about four hours each way.\n\nOne or two stops can be planned along the way — for example in Pärnu or Rundāle. The route is agreed in advance.\n\nVolvo XC60, up to four people with luggage. Price per one-way ride.',
 E'Traslado privado de Riga a Tallin o Vilna, unas cuatro horas por trayecto.\n\nSe pueden planear una o dos paradas, por ejemplo en Pärnu o Rundāle.\n\nVolvo XC60, hasta cuatro personas con equipaje.',
 240,200,false,1,4,ARRAY['getaround']::public.enter_gauja_category[],NULL,'Rīga',56.9496,24.1052,'Rīga','Tallinn / Viļņa','Volvo XC60, 1–4 personas',
 'Baltijas pilsētu transfērs no Rīgas','Baltic cities transfer from Riga','Traslado entre capitales bálticas desde Riga',
 'Privāts transfērs no Rīgas uz Tallinu vai Viļņu ar pieturām pēc vienošanās.',
 'Private transfer from Riga to Tallinn or Vilnius with stops by arrangement.',
 'Traslado privado de Riga a Tallin o Vilna con paradas acordadas.',
 true,20)
ON CONFLICT DO NOTHING;

-- ===== FAQ =====
INSERT INTO public.faq (question_lv, question_en, question_es, answer_lv, answer_en, answer_es, category, sort_order, is_active) VALUES
('Kā rezervēt ekskursiju vai pārgājienu?','How do I book a tour or hike?','¿Cómo reservo una excursión o caminata?',
 'Aizpildiet rezervācijas formu mājaslapā vai rakstiet e-pastā. Atbildu 24 stundu laikā ar apstiprinājumu vai alternatīvu laiku.',
 'Fill in the booking form on the website or send an email. I reply within 24 hours with a confirmation or an alternative time.',
 'Rellene el formulario de reserva o escriba un correo. Respondo en 24 horas con la confirmación o una alternativa.','booking',1,true),
('Kādās valodās notiek ekskursijas?','In which languages are the tours held?','¿En qué idiomas se realizan las excursiones?',
 'Latviski, angliski, krieviski un spāniski. Valodu norādiet rezervācijā.',
 'In Latvian, English, Russian and Spanish. Please state your language when booking.',
 'En letón, inglés, ruso y español. Indique el idioma al reservar.','practical',2,true),
('Kas jāņem līdzi pārgājienā?','What should I bring on a hike?','¿Qué debo llevar a una caminata?',
 'Ērti, aizsegti apavi, laikapstākļiem piemērots apģērbs, ūdens un neliela uzkoda. Garākos maršrutos — vismaz 1,5 l ūdens un pusdienas.',
 'Comfortable closed shoes, clothing suited to the weather, water and a snack. On longer routes at least 1.5 l of water and a packed lunch.',
 'Calzado cerrado y cómodo, ropa adecuada al tiempo, agua y algo de comer. En rutas largas, 1,5 l de agua y comida.','practical',3,true),
('Vai ekskursijas notiek sliktos laikapstākļos?','Do tours run in bad weather?','¿Las excursiones se realizan con mal tiempo?',
 'Jā, lietus vai sniegs nav šķērslis — pielāgojam maršrutu. Atceļam tikai bīstamos apstākļos, piemēram, vētrā; tādā gadījumā piedāvāju citu datumu vai atmaksu.',
 'Yes — rain or snow is not an obstacle and the route is adapted. I only cancel in dangerous conditions such as storms, offering another date or a refund.',
 'Sí; la lluvia o la nieve no son un obstáculo y adaptamos la ruta. Solo cancelo con condiciones peligrosas, ofreciendo otra fecha o reembolso.','practical',4,true),
('Vai cenā ir iekļautas pusdienas?','Are meals included in the price?','¿La comida está incluida?',
 'Nē, ēdināšana nav iekļauta. Garākos maršrutos iesaku ņemt līdzi pusdienas; ekskursijās pilsētās varu ieteikt vietējās kafejnīcas.',
 'No, meals are not included. On longer routes bring a packed lunch; on town tours I can recommend local cafés.',
 'No, la comida no está incluida. En rutas largas lleve comida; en las visitas urbanas puedo recomendar cafeterías.','pricing',5,true),
('Kā atcelt vai pārcelt rezervāciju?','How do I cancel or reschedule a booking?','¿Cómo cancelo o cambio una reserva?',
 'Rakstiet man vismaz 48 stundas iepriekš — pārcelšana vai atcelšana ir bez maksas. Vēlāk atcelšanas gadījumā var tikt piemērota daļēja maksa.',
 'Write to me at least 48 hours in advance — rescheduling or cancelling is free. Later cancellations may incur a partial charge.',
 'Escríbame con al menos 48 horas de antelación: cambiar o cancelar es gratuito. Después puede aplicarse un cargo parcial.','booking',6,true),
('Vai vienā dienā var apvienot vairākas ekskursijas?','Can several tours be combined in one day?','¿Se pueden combinar varias excursiones en un día?',
 'Jā. Populārākais variants ir Sigulda un Turaida no rīta un Cēsis pēcpusdienā. Uzrakstiet, ko vēlaties redzēt, un salikšu reālu dienas plānu.',
 'Yes. The most popular combination is Sigulda and Turaida in the morning and Cēsis in the afternoon. Tell me what you want to see and I will put together a realistic plan.',
 'Sí. La combinación más habitual es Sigulda y Turaida por la mañana y Cēsis por la tarde. Dígame qué quiere ver y prepararé un plan realista.','booking',7,true),
('Vai bērniem ir atlaides?','Are there discounts for children?','¿Hay descuentos para niños?',
 'Bērniem līdz 7 gadu vecumam dalība ir bez maksas, no 7 līdz 14 gadiem — puse no cenas par personu. Transfēros cena ir par braucienu, tāpēc bērnu skaits cenu nemaina.',
 'Children under 7 join free of charge, from 7 to 14 pay half the per-person price. Transfers are priced per ride, so the number of children does not change the price.',
 'Los menores de 7 años no pagan; de 7 a 14 años, la mitad del precio por persona. Los traslados se cobran por trayecto.','pricing',8,true),
('Vai transfērs pieejams agri no rīta vai vēlu vakarā?','Is a transfer available early in the morning or late at night?','¿Hay traslados de madrugada o de noche?',
 'Jā, braucu arī agros rītos un vēlos vakaros, tostarp uz lidostu. Laiku ārpus 7.00–22.00 lūdzu saskaņot vismaz dienu iepriekš.',
 'Yes, I drive early mornings and late evenings, including airport runs. Please arrange times outside 07:00–22:00 at least a day ahead.',
 'Sí, conduzco de madrugada y por la noche, también al aeropuerto. Fuera del horario 07:00–22:00, avise con un día de antelación.','practical',9,true),
('Kā notiek apmaksa?','How does payment work?','¿Cómo se realiza el pago?',
 'Maksāt var skaidrā naudā tikšanās vietā vai ar pārskaitījumu pēc rēķina. Priekšapmaksa nav nepieciešama, izņemot lielas grupas un garos transfērus.',
 'You can pay in cash at the meeting point or by bank transfer against an invoice. No prepayment is required except for large groups and long transfers.',
 'Puede pagar en efectivo en el punto de encuentro o por transferencia con factura. No se requiere pago anticipado salvo grupos grandes y traslados largos.','pricing',10,true)
ON CONFLICT DO NOTHING;